<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SellerCenter.Helper\SellerCenter.Helper.csproj" />
    <ProjectReference Include="..\SellerCenter.Infrastructure\SellerCenter.Infrastructure.csproj" />
  </ItemGroup>

</Project>
